fsl_sai: fix building warning for array-bounds
If NDEBUG is defined, assert() will be NULL function, so if building with
-Wall and -Werror, there will the following buidling error:

drivers/sai/fsl_sai.c:2312:16: error: array subscript 4 is above array bounds
of 'sai_handle_t *[4][2]' {aka 'struct _sai_handle *[4][2]'} [-Werror=array-bounds]
 2312 |     s_saiHandle[SAI_GetInstance(base)][0] = handle;

Signed-off-by: Jiafei Pan <Jiafei.Pan@nxp.com>